<a href="https://colab.research.google.com/github/PrzemyslawSarnacki/NumericalMethods/blob/master/DecompositionLU.ipynb" target="_parent">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a> 

In [15]:
import numpy as np
import cProfile
from scipy.linalg import lu

In [2]:
def decompose(matrix):
    """
    decompose matrix into l and u matrices
    """
    # checking size of array
    shape = np.shape(matrix)
    # assigning rows and columns to shape 
    rows, columns = shape 
    # declaring both matrices
    l = np.zeros(shape)
    u = np.zeros(shape)

    for i in range(columns):
    # filling l matrix 
        for j in range(i):
            sum_first = 0
            for k in range(j):
                sum_first += l[i][k] * u[k][j]
            l[i][j] = (matrix[i][j] - sum_first) / u[j][j]
        l[i][i] = 1
        # filling u matrix
        for j in range(i, columns):
            sum_second = 0
            for k in range(i):
                sum_second += l[i][k] * u[k][j]
            u[i][j] = matrix[i][j] - sum_second
    return l, u


Sprawdźmy jaki powinien być prawidłowy wynik implementacji (użyjemy wbudowanej funkcji z biblioteki SciPy)

In [3]:
A = np.array([[7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]])
p, l, u = lu(A)
print(l)
print(u)

[[ 1.          0.          0.          0.        ]
 [ 0.42857143  1.          0.          0.        ]
 [-0.14285714  0.21276596  1.          0.        ]
 [ 0.28571429 -0.72340426  0.08982036  1.        ]]
[[ 7.          3.         -1.          2.        ]
 [ 0.          6.71428571  1.42857143 -4.85714286]
 [ 0.          0.          3.55319149  0.31914894]
 [ 0.          0.          0.          1.88622754]]


Wywołanie funkcji zawierającej własną implementację - jak widzimy wynik jest identyczny

In [4]:
l, u = decompose(A)
print(l)
print(u)

[[ 1.          0.          0.          0.        ]
 [ 0.42857143  1.          0.          0.        ]
 [-0.14285714  0.21276596  1.          0.        ]
 [ 0.28571429 -0.72340426  0.08982036  1.        ]]
[[ 7.          3.         -1.          2.        ]
 [ 0.          6.71428571  1.42857143 -4.85714286]
 [ 0.          0.          3.55319149  0.31914894]
 [ 0.          0.          0.          1.88622754]]


Jak możemy poniżej zauważyć wymnożenie macierzy Lower i Upper daje nam wynik w postaci macierzy wejściowej

In [6]:
print(A)
np.matmul(l,u)


[[ 7  3 -1  2]
 [ 3  8  1 -4]
 [-1  1  4 -1]
 [ 2 -4 -1  6]]


array([[ 7.,  3., -1.,  2.],
       [ 3.,  8.,  1., -4.],
       [-1.,  1.,  4., -1.],
       [ 2., -4., -1.,  6.]])

Porównanie wydajności obu metod

In [16]:
cProfile.run("decompose(A)")

10 function calls in 0.001 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 <__array_function__ internals>:2(shape)
        1    0.000    0.000    0.000    0.000 <ipython-input-2-d840b7f18041>:1(decompose)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 fromnumeric.py:1899(_shape_dispatcher)
        1    0.000    0.000    0.000    0.000 fromnumeric.py:1903(shape)
        1    0.000    0.000    0.001    0.001 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
        2    0.000    0.000    0.000    0.000 {built-in method numpy.zeros}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [17]:
cProfile.run("lu(A)")

17 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 _asarray.py:16(asarray)
        1    0.000    0.000    0.000    0.000 decomp_lu.py:152(lu)
        1    0.000    0.000    0.000    0.000 flinalg.py:22(has_column_major_storage)
        1    0.000    0.000    0.000    0.000 flinalg.py:29(get_flinalg_funcs)
        1    0.000    0.000    0.000    0.000 function_base.py:435(asarray_chkfinite)
        1    0.000    0.000    0.000    0.000 misc.py:184(_datacopied)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        2    0.000    0.000    0.000    0.000 {built-in method builtins.getattr}
        2    0.000    0.000    0.000    0.000 {built-in method builtins.len}
        1    0.000    0.000    0.000    0.000 {built-in method numpy.array}
        2    0.000    0.

Jak widzimy wbudowana funkcja lu() jest wydajniejsza od implementacji własnej 