<a href="https://colab.research.google.com/github/PrzemyslawSarnacki/NumericalMethods/blob/master/DecompositionLU.ipynb" target="_parent">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a> 

In [12]:
import math
import matplotlib.pyplot as plt
import numpy as np
import timeit
from scipy.linalg import lu

In [16]:
matrix = np.array([[2, -2, 1], [0, 1, 2], [5, 3, 1]])
def decompose(matrix):
    """
    docstring
    """
    shape = np.shape(matrix)
    rows, columns = shape 
    l = np.zeros(shape)
    u = np.zeros(shape)
    for i in range(columns):
        for j in range(i):
            sum_first = 0
            for k in range(j):
                sum_first += l[i][k] * u[k][j]
            l[i][j] = (matrix[i][j] - sum_first) / u[j][j]
        l[i][i] = 1
        for j in range(i, columns):
            sum_second = 0
            for k in range(i):
                sum_second += l[i][k] * u[k][j]
            u[i][j] = matrix[i][j] - sum_second
    return l, u


In [17]:
A = np.array([[7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]])
p, l, u = lu(A)
print(l)
print(u)

[[ 1.          0.          0.          0.        ]
 [ 0.42857143  1.          0.          0.        ]
 [-0.14285714  0.21276596  1.          0.        ]
 [ 0.28571429 -0.72340426  0.08982036  1.        ]]
[[ 7.          3.         -1.          2.        ]
 [ 0.          6.71428571  1.42857143 -4.85714286]
 [ 0.          0.          3.55319149  0.31914894]
 [ 0.          0.          0.          1.88622754]]


In [31]:
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
l,u = decompose(A)
print(l)
print(u)

[[1.         0.         0.         0.        ]
 [2.5        1.         0.         0.        ]
 [3.5        1.19047619 1.         0.        ]
 [2.5        0.80952381 2.5        1.        ]]
[[  2.           5.           8.           7.        ]
 [  0.         -10.5        -18.          -9.5       ]
 [  0.           0.          -0.57142857  -7.19047619]
 [  0.           0.           0.          16.16666667]]


In [32]:
np.matmul(l,u)

array([[2., 5., 8., 7.],
       [5., 2., 2., 8.],
       [7., 5., 6., 6.],
       [5., 4., 4., 8.]])

In [ ]:
min(timeit.timeit("decompose(A)"), globals=globals())

NameError: name 'decompose' is not defined