<a href="https://colab.research.google.com/github/PrzemyslawSarnacki/NumericalMethods/blob/master/Gauss-Seidel.ipynb" target="_parent">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a> 

In [4]:
import numpy as np

Implementujemy metodę Gaussa-Seidel'a w postaci funkcji

In [63]:
def seidel(matrix, b, N=5):
    """
    jacobi iterative method in function
    """
    x=np.zeros_like(b)
    m, n = matrix.shape
    # Iterate N number of times
    for _ in range(N):
        # Iterate through rows
        for j in range(m):
            # we will slice matrices at appropriate indices
            m1 = np.matmul(matrix[j, :j], x[:j])
            m2 = np.matmul(matrix[j, j + 1 :], x[j + 1 :])
            x[j] = (b[j] - m1 - m2) / matrix[j, j]
    return x



Sprawdźmy jaki powinien być prawidłowy wynik implementacji (użyjemy wbudowanej funkcji z biblioteki numpy)

In [32]:
a = np.array([
[4,	-1,	-0.2,	2],
[-1,	5,	0,	-2],
[0.2,	1,	10,	-1],
[0,	-2,	-1,	4],
], float)
b = np.array([30, 0, -10, 5], float)


np.linalg.solve(a, b)

array([ 6.96156056,  2.22112253, -1.15414086,  2.07202605])

In [65]:
a[1,:1]

array([-1.])

In [64]:
a[1, 2:]

array([ 0., -2.])

Wywołanie funkcji zawierającej własną implementację - jak widzimy wynik jest zbliżony i przy większej liczbie iteracji staje się coraz dokładniejszy

In [35]:
a = np.array([
[4, -1, -0.2, 2],
[-1, 5, 0, -2],
[0.2, 1, 10, -1],
[0, -2, -1, 4],
], float)
b = np.array([30, 0, -10, 5], float)


seidel(a, b)

array([ 6.96164262,  2.21960678, -1.15437397,  2.0712099 ])

In [56]:
a[1, :1]

array([-1.])

In [30]:
a = np.array([
[4, -1, -0.2, 2],
[-1, 5, 0, -2],
[0.2, 1, 10, -1],
[0, -2, -1, 4],
], float)
b = np.array([30, 0, -10, 5], float)


seidel(a, b, N=10)

array([ 6.96156073,  2.22111941, -1.15414134,  2.07202437])

In [31]:
a = np.array([
[4, -1, -0.2, 2],
[-1, 5, 0, -2],
[0.2, 1, 10, -1],
[0, -2, -1, 4],
], float)
b = np.array([30, 0, -10, 5], float)


seidel(a, b, N=100)

array([ 6.96156056,  2.22112253, -1.15414086,  2.07202605])