<a href="https://colab.research.google.com/github/PrzemyslawSarnacki/NumericalMethods/blob/master/Jacobi.ipynb" target="_parent">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a> 

In [2]:
import numpy as np

Implementujemy metodę eliminacji Gaussa w postaci funkcji

In [5]:
def jacobi(matrix, b, N=5):
    """
    jacobi iterative method in function
    """
    # N is numer of interations and it's default value is 5
    # default choices will be just zeros
    x=np.zeros(b.shape)
    # We will Create diagonal array
    d = np.diag(matrix)
    # We are substracting diagonal matrix from input matrix 
    r = matrix - np.diagflat(d)

    # Loop for N times 
    for _ in range(N):
        x = (b - np.dot(r,x)) / d
    return x


Sprawdźmy jaki powinien być prawidłowy wynik implementacji (użyjemy wbudowanej funkcji z biblioteki numpy)

In [15]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])

np.linalg.solve(a, b)

array([2., 3.])

Wywołanie funkcji zawierającej własną implementację - jak widzimy wynik jest zbliżony i przy większej liczbie iteracji staje się coraz dokładniejszy

In [34]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])


jacobi(a, b)

array([2.02777778, 3.02777778])

In [31]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])


jacobi(a, b, N=10)

array([1.9997428, 2.9996142])

In [35]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])


jacobi(a, b, N=100)

array([2., 3.])

Gdy sprawdzimy inne macierze o większych rozdzielczościach wynik będzie podobny

In [37]:
a = np.array([
[4,	-1,	-0.2,	2],
[-1,	5,	0,	-2],
[0.2,	1,	10,	-1],
[0,	-2,	-1,	4],
], float)
b = np.array([30, 0, -10, 5], float)


np.linalg.solve(a, b)

array([ 6.96156056,  2.22112253, -1.15414086,  2.07202605])

In [44]:
a = np.array([
[4,	-1,	-0.2,	2],
[-1,	5,	0,	-2],
[0.2,	1,	10,	-1],
[0,	-2,	-1,	4],
], float)
b = np.array([30, 0, -10, 5], float)


jacobi(a, b)

array([ 7.10382  ,  2.10586  , -1.1840385,  2.1121   ])

In [42]:
a = np.array([
[4,	-1,	-0.2,	2],
[-1,	5,	0,	-2],
[0.2,	1,	10,	-1],
[0,	-2,	-1,	4],
], float)
b = np.array([30, 0, -10, 5], float)


jacobi(a, b, N=100)

array([ 6.96156056,  2.22112253, -1.15414086,  2.07202605])